// src/config/routeConfig.js
// Responsabilidade: lista de rotas por operador PSM

export const ROUTES_BY_PSM = {
  // ISISTEL: 17 rotas (Cabinda) - ORDEM ALFABÉTICA
  ISISTEL: [
    'BSC_Cabinda - Quatro',
    'BSC_Cabinda - Resistencia (Cabo_1)',
    'BSC_Cabinda - Resistencia (Cabo_2)',
    'Cine_Popular - BSC_Cabinda',
    'Corda_Expansão_Cabassango',
    'Hoji_Cacongo - Belize',
    'Hoji_Cacongo - Massabe_Fronteira',
    'Lucola - Hoji_Cacongo',
    'Lucola - Tchizu_O',
    'Massabi_Fronteira - Belize',
    'PV_Grande_NT - Tchizu_O',
    'PV_Grande_NT - Yema_Fronteira',
    'Quatro - PV_Grande_NT',
    'Quatro - Tchizu_O',
    'Resistencia - Cine_Popular',
    'Resistencia - Lucola',
    'Tchizu_O - Cine_Popular'
  ],

  // FIBRASOL: 53 rotas (Norte/Leste) - ORDEM ALFABÉTICA
  FIBRASOL: [
    'Alto Dondo - Quibala',
    'Ambriz - N\'zeto',
    'BSC_Malange - Canambua',
    'Calucinga - Mussende',
    'Camabatela - Lucala',
    'Canambua - Vila_Matilde',
    'Cuango - Cafunfo',
    'Cuango - Caungula',
    'Cuimba - Nguabi',
    'Damba - Uige(Negage_CRT)',
    'Hospital - Lumbo',
    'Kimbumba - Soyo_Centro',
    'Kimbundo - Uige (Inca)',
    'Kwanada_O (ODFB2)- JFO11 Porto',
    'Kwanda_DCS - Kwanda_O',
    'Kwanda_DCS - Loja',
    'Kwanda_DCS - Porto',
    'Kwanda_DCS- ODFB1- JFO(288)ALNG',
    'Kwanda_O (ODFB3)- JFO(288)- Azul Energi',
    'Kwanda_O - Loja',
    'Kwanda_O - Porto',
    'Lucala - Ndalatando',
    'Lucenga - Mucula',
    'Lumbo - BSC_Malange',
    'Malange (Lumbo) - Lucala',
    'Malange (Vila Matilde) - Mulo',
    'Malange_CTR - Lumbo e Bsc',
    'Maria teresa Gulungo_Alto - Nadalatando',
    'Maxinde (Expansão) - BSC',
    'Maxinde (Expansão) - Lumbo',
    'Mbanza Congo - Noqui',
    'Mbanza Congo_Sul - BSC ODF 3 (11 de Novembro)',
    'Mbanza Congo_Sul - BSC ODF 4',
    'Mbaza Centro - Cuimba',
    'Mucula - Soyo',
    'Mulo - Cuango',
    'Muquiama - Kimbundo',
    'Mussende - Malange (Catepa)',
    'Ndala Norte - KN_Azul',
    'Ndala Norte - Ndala_Leste',
    'Ndala_CTR(BSC Ndalatando) - KN_Azul',
    'Ndalatando - Alto_Dondo',
    'Negage - Camabatela',
    'Nguabi - Damba',
    'Nzeto - Lussenga',
    'Nzeto - Mucula',
    'Nzeto - Soyo',
    'Tomboco - Lussenga',
    'Tomboco - Mbanza Congo',
    'Uíge - Negage',
    'Uíge_CTR - Unipop_Oeste ODF 1',
    'Uíge_CTR - Unipop_Oeste ODF 2',
    'Vila_Matilde - Hospital'
  ],

  // ANGLOBAL: 34 rotas (Leste/Sul) - ORDEM ALFABÉTICA
  ANGLOBAL: [
    'Br_Capango_Sul - Sacalunda',
    'Cambacumba - Dundo',
    'Camissombo (Lucapa) - Dundo',
    'Cangumbe - Luena',
    'Caungula - Cuilo',
    'Cazombo - Karipande',
    'Cuemba - Cangumbe',
    'Cuilo - Cambacumba',
    'Dom_Bosco - Luena_CTR',
    'Dundo_CRT ODF1 - Dundo_CRT ODF2',
    'Luau - Massibi',
    'Lucusse - Lutembo',
    'Luena - Dala',
    'Luena - Lucusse',
    'Luena_CTR - Luena_Largo',
    'Luena_Largo - Zorro',
    'Lumbala Nguimbo - Ninda',
    'Lutembo - Lumbala Nguimbo',
    'Massibi - Cazombo',
    'Muconda - Luau',
    'Neto - Santo Antonio',
    'Neto - Terra_Nova (Saurimo_Sul)',
    'Ninda - Malundo',
    'Sacalunda - Dom_Bosco',
    'Santo Antonio - Terra Nova',
    'Saurimo - Dala',
    'Saurimo - Lucapa (Camissombo)',
    'Saurimo(Br_Muconda) - Muconda',
    'Saurimo Norte -- IEIA',
    'Saurimo_CRT - IEIA',
    'Saurimo_Norte - Neto',
    'Stº António - Saurimo_sul',
    'Terra_Nova - Saurimo_CRT',
    'Zorro - Br_Capango_Sul'
  ]
};
