-- ============================================================
-- MIGRAÇÃO 003 — Seed das rotas estáticas em route_config
-- 104 rotas: ISISTEL (17) + FIBRASOL (53) + ANGLOBAL (34)
-- ============================================================

INSERT INTO route_config (psm, route_name, province, is_active, display_order)
VALUES
('ISISTEL', 'BSC_Cabinda - Quatro', 'Cabinda', true, 0),
('ISISTEL', 'BSC_Cabinda - Resistencia (Cabo_1)', 'Cabinda', true, 1),
('ISISTEL', 'BSC_Cabinda - Resistencia (Cabo_2)', 'Cabinda', true, 2),
('ISISTEL', 'Cine_Popular - BSC_Cabinda', 'Cabinda', true, 3),
('ISISTEL', 'Corda_Expansão_Cabassango', 'Cabinda', true, 4),
('ISISTEL', 'Hoji_Cacongo - Belize', 'Cabinda', true, 5),
('ISISTEL', 'Hoji_Cacongo - Massabe_Fronteira', 'Cabinda', true, 6),
('ISISTEL', 'Lucola - Hoji_Cacongo', 'Cabinda', true, 7),
('ISISTEL', 'Lucola - Tchizu_O', 'Cabinda', true, 8),
('ISISTEL', 'Massabi_Fronteira - Belize', 'Cabinda', true, 9),
('ISISTEL', 'PV_Grande_NT - Tchizu_O', 'Cabinda', true, 10),
('ISISTEL', 'PV_Grande_NT - Yema_Fronteira', 'Cabinda', true, 11),
('ISISTEL', 'Quatro - PV_Grande_NT', 'Cabinda', true, 12),
('ISISTEL', 'Quatro - Tchizu_O', 'Cabinda', true, 13),
('ISISTEL', 'Resistencia - Cine_Popular', 'Cabinda', true, 14),
('ISISTEL', 'Resistencia - Lucola', 'Cabinda', true, 15),
('ISISTEL', 'Tchizu_O - Cine_Popular', 'Cabinda', true, 16),
('FIBRASOL', 'Alto Dondo - Quibala', 'Cuanza Norte', true, 0),
('FIBRASOL', 'Ambriz - N''zeto', 'Zaire', true, 1),
('FIBRASOL', 'BSC_Malange - Canambua', 'Malanje', true, 2),
('FIBRASOL', 'Calucinga - Mussende', 'Malanje', true, 3),
('FIBRASOL', 'Camabatela - Lucala', 'Uíge', true, 4),
('FIBRASOL', 'Canambua - Vila_Matilde', 'Malanje', true, 5),
('FIBRASOL', 'Cuango - Cafunfo', 'Malanje', true, 6),
('FIBRASOL', 'Cuango - Caungula', 'Malanje', true, 7),
('FIBRASOL', 'Cuimba - Nguabi', 'Zaire', true, 8),
('FIBRASOL', 'Damba - Uige(Negage_CRT)', 'Uíge', true, 9),
('FIBRASOL', 'Hospital - Lumbo', 'Malanje', true, 10),
('FIBRASOL', 'Kimbumba - Soyo_Centro', 'Zaire', true, 11),
('FIBRASOL', 'Kimbundo - Uige (Inca)', 'Uíge', true, 12),
('FIBRASOL', 'Kwanada_O (ODFB2)- JFO11 Porto', 'Zaire', true, 13),
('FIBRASOL', 'Kwanda_DCS - Kwanda_O', 'Zaire', true, 14),
('FIBRASOL', 'Kwanda_DCS - Loja', 'Zaire', true, 15),
('FIBRASOL', 'Kwanda_DCS - Porto', 'Zaire', true, 16),
('FIBRASOL', 'Kwanda_DCS- ODFB1- JFO(288)ALNG', 'Zaire', true, 17),
('FIBRASOL', 'Kwanda_O (ODFB3)- JFO(288)- Azul Energi', 'Zaire', true, 18),
('FIBRASOL', 'Kwanda_O - Loja', 'Zaire', true, 19),
('FIBRASOL', 'Kwanda_O - Porto', 'Zaire', true, 20),
('FIBRASOL', 'Lucala - Ndalatando', 'Cuanza Norte', true, 21),
('FIBRASOL', 'Lucenga - Mucula', 'Zaire', true, 22),
('FIBRASOL', 'Lumbo - BSC_Malange', 'Malanje', true, 23),
('FIBRASOL', 'Malange (Lumbo) - Lucala', 'Malanje', true, 24),
('FIBRASOL', 'Malange (Vila Matilde) - Mulo', 'Malanje', true, 25),
('FIBRASOL', 'Malange_CTR - Lumbo e Bsc', 'Malanje', true, 26),
('FIBRASOL', 'Maria teresa Gulungo_Alto - Nadalatando', 'Cuanza Norte', true, 27),
('FIBRASOL', 'Maxinde (Expansão) - BSC', 'Malanje', true, 28),
('FIBRASOL', 'Maxinde (Expansão) - Lumbo', 'Malanje', true, 29),
('FIBRASOL', 'Mbanza Congo - Noqui', 'Zaire', true, 30),
('FIBRASOL', 'Mbanza Congo_Sul - BSC ODF 3 (11 de Novembro)', 'Zaire', true, 31),
('FIBRASOL', 'Mbanza Congo_Sul - BSC ODF 4', 'Zaire', true, 32),
('FIBRASOL', 'Mbaza Centro - Cuimba', 'Zaire', true, 33),
('FIBRASOL', 'Mucula - Soyo', 'Zaire', true, 34),
('FIBRASOL', 'Mulo - Cuango', 'Malanje', true, 35),
('FIBRASOL', 'Muquiama - Kimbundo', 'Uíge', true, 36),
('FIBRASOL', 'Mussende - Malange (Catepa)', 'Malanje', true, 37),
('FIBRASOL', 'Ndala Norte - KN_Azul', 'Cuanza Norte', true, 38),
('FIBRASOL', 'Ndala Norte - Ndala_Leste', 'Cuanza Norte', true, 39),
('FIBRASOL', 'Ndala_CTR(BSC Ndalatando) - KN_Azul', 'Cuanza Norte', true, 40),
('FIBRASOL', 'Ndalatando - Alto_Dondo', 'Cuanza Norte', true, 41),
('FIBRASOL', 'Negage - Camabatela', 'Uíge', true, 42),
('FIBRASOL', 'Nguabi - Damba', 'Uíge', true, 43),
('FIBRASOL', 'Nzeto - Lussenga', 'Zaire', true, 44),
('FIBRASOL', 'Nzeto - Mucula', 'Zaire', true, 45),
('FIBRASOL', 'Nzeto - Soyo', 'Zaire', true, 46),
('FIBRASOL', 'Tomboco - Lussenga', 'Zaire', true, 47),
('FIBRASOL', 'Tomboco - Mbanza Congo', 'Zaire', true, 48),
('FIBRASOL', 'Uíge - Negage', 'Uíge', true, 49),
('FIBRASOL', 'Uíge_CTR - Unipop_Oeste ODF 1', 'Uíge', true, 50),
('FIBRASOL', 'Uíge_CTR - Unipop_Oeste ODF 2', 'Uíge', true, 51),
('FIBRASOL', 'Vila_Matilde - Hospital', 'Malanje', true, 52),
('ANGLOBAL', 'Br_Capango_Sul - Sacalunda', 'Moxico', true, 0),
('ANGLOBAL', 'Cambacumba - Dundo', 'Lunda Norte', true, 1),
('ANGLOBAL', 'Camissombo (Lucapa) - Dundo', 'Lunda Norte', true, 2),
('ANGLOBAL', 'Cangumbe - Luena', 'Moxico', true, 3),
('ANGLOBAL', 'Caungula - Cuilo', 'Lunda Norte', true, 4),
('ANGLOBAL', 'Cazombo - Karipande', 'Lunda Sul', true, 5),
('ANGLOBAL', 'Cuemba - Cangumbe', 'Moxico', true, 6),
('ANGLOBAL', 'Cuilo - Cambacumba', 'Lunda Norte', true, 7),
('ANGLOBAL', 'Dom_Bosco - Luena_CTR', 'Moxico', true, 8),
('ANGLOBAL', 'Dundo_CRT ODF1 - Dundo_CRT ODF2', 'Lunda Norte', true, 9),
('ANGLOBAL', 'Luau - Massibi', 'Lunda Sul', true, 10),
('ANGLOBAL', 'Lucusse - Lutembo', 'Moxico', true, 11),
('ANGLOBAL', 'Luena - Dala', 'Moxico', true, 12),
('ANGLOBAL', 'Luena - Lucusse', 'Moxico', true, 13),
('ANGLOBAL', 'Luena_CTR - Luena_Largo', 'Moxico', true, 14),
('ANGLOBAL', 'Luena_Largo - Zorro', 'Moxico', true, 15),
('ANGLOBAL', 'Lumbala Nguimbo - Ninda', 'Moxico', true, 16),
('ANGLOBAL', 'Lutembo - Lumbala Nguimbo', 'Moxico', true, 17),
('ANGLOBAL', 'Massibi - Cazombo', 'Lunda Sul', true, 18),
('ANGLOBAL', 'Muconda - Luau', 'Lunda Sul', true, 19),
('ANGLOBAL', 'Neto - Santo Antonio', 'Lunda Sul', true, 20),
('ANGLOBAL', 'Neto - Terra_Nova (Saurimo_Sul)', 'Lunda Sul', true, 21),
('ANGLOBAL', 'Ninda - Malundo', 'Moxico', true, 22),
('ANGLOBAL', 'Sacalunda - Dom_Bosco', 'Moxico', true, 23),
('ANGLOBAL', 'Santo Antonio - Terra Nova', 'Lunda Sul', true, 24),
('ANGLOBAL', 'Saurimo - Dala', 'Lunda Sul', true, 25),
('ANGLOBAL', 'Saurimo - Lucapa (Camissombo)', 'Lunda Sul', true, 26),
('ANGLOBAL', 'Saurimo(Br_Muconda) - Muconda', 'Lunda Sul', true, 27),
('ANGLOBAL', 'Saurimo Norte -- IEIA', 'Lunda Sul', true, 28),
('ANGLOBAL', 'Saurimo_CRT - IEIA', 'Lunda Sul', true, 29),
('ANGLOBAL', 'Saurimo_Norte - Neto', 'Lunda Sul', true, 30),
('ANGLOBAL', 'Stº António - Saurimo_sul', 'Lunda Sul', true, 31),
('ANGLOBAL', 'Terra_Nova - Saurimo_CRT', 'Lunda Sul', true, 32),
('ANGLOBAL', 'Zorro - Br_Capango_Sul', 'Moxico', true, 33)
ON CONFLICT (psm, route_name) DO UPDATE SET
  province      = EXCLUDED.province,
  is_active     = EXCLUDED.is_active,
  display_order = EXCLUDED.display_order;
